### ISSUE TITLE
BF3 Venice Unleashed

### ISSUE THREAD

**Issue by Bitcrusher369** [tyger07/BF3-Server-Stats#3]
### Expected Behavior:
webpage to work correctly

### Actual Behavior:
No 'BF3' servers were found in this database! Please notify this website's administrator.
looked in database seems to show server name

### Steps Performed to Reproduce this Behavior:
i would believe its because of VU not being battlog

**Comment by Bitcrusher369** [comment]
can find me at tsp-games.com i would really like a hand getting this going for the community thanks

**Comment by tyger07** [comment]
Hi,
My stats page code cannot display what XpKiller's plugin does not store in the database.
My stats page code just presents the data which exists.  If the data doesn't exist, my stats page code cannot display it.

1) Hacked servers are illegal.
2) Server which don't use Punkbuster (including hacked servers) are not compatible with XpKiller's plugin.

There is nothing I can do.
This is not a valid issue.  This "issue" is closed.
